version: "3.8"

services:
  terrarium:
    build:
      context: https://github.com/cohere-ai/cohere-terrarium.git#main
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 1s
      retries: 3
    volumes:
      - pyodide_cache:/app/pyodide_cache

volumes:
  pyodide_cache:
